ci: switch to docker bake ci: sends e-mail if one of the apps fail to build ci: allow `-rc` tags to trigger pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -25,7 +25,7 @@ stages:
 .app-rules:
   rules:
     - if: $CI_COMMIT_TAG == "staging"
-    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
+    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc\.\d+)?$/
 
 .devops-rules:
   rules:
@@ -122,26 +122,71 @@ release-apps:
   tags: [docker]
   extends:
     - .app-rules
-  variables:
-    TURBO_TOKEN: $TURBO_TOKEN
+  # Required variables (defined in GitLab CI/CD Settings)
+  # - SMTP_CONF: ssmtp configuration to send warning e-mails (https://linux.die.net/man/5/ssmtp.conf)
+  # - SMTP_FROM: mail author name <email>
+  # - SMTP_TO: comma seperated e-mail addresses
+  # - TURBO_CONFIG: Turbo cache configuration
+  # - TURBO_FORCE: Ignore turbo cache
+  # - TURBO_TOKEN: Auth token for turbo cache
   before_script:
-    - apk add --no-cache jq
+    - apk add --no-cache jq ssmtp gomplate
     - *docker-login
   script:
     - mkdir release-logs
+    # Build/Push every app defined in TARGET_APPS sequentially
     - |
       for APP_NAME in $TARGET_APPS; do
         LOG_PATH="release-logs/$APP_NAME.log"
         ERR_PATH="release-logs/$APP_NAME.error.log"
+        EXIT_CODE=0
+
+        # Variables for docker bake
+        export APP_NAME="$APP_NAME"
+        export APP_ROLES="$(jq -Mc '.roles // []' "apps/$APP_NAME/manifest.json" 2> /dev/null || echo '[]')"
+
         rm -rf out && mv out-$APP_NAME out
+        # Output build logs to both the console and a log file
         {
-          ./scripts/release-image $APP_NAME 2>&1 || {
-            export CI_ERROR=1
+          docker buildx bake "$APP_NAME" --push 2>&1 || {
             mv $LOG_PATH $ERR_PATH
           }
         } | tee $LOG_PATH
+
+        if [ -e "$ERR_PATH" ]; then
+          if [ -n "$ERRORS" ]; then
+            ERRORS="$ERRORS,$APP_NAME"
+          else
+            ERRORS="$APP_NAME"
+          fi
+        fi
       done
-      if [ -n "$CI_ERROR" ]; then exit 1; fi;
+    # Send mail with list of failed apps, TODO: attach logs to mail
+    - |
+      if [ -n "$ERRORS" ]; then
+          ssmtp -C"$SMTP_CONF" "$SSMTP_TO" <<EOF
+      From: $SMTP_FROM
+      To: $SMTP_TO
+      Subject: $CI_PROJECT_NAME | Pipeline Warning | $CI_COMMIT_SHORT_SHA
+      Content-Type: text/html; charset=UTF-8
+
+      <html>
+        <body>
+          <p>Build failed for following apps: </p>
+          <ul>
+            $(gomplate -i '{{range strings.Split "," .Env.ERRORS}}<li>{{.}}</li>{{end}}')
+          </ul>
+          <p>Pipeline: <a href="$CI_PROJECT_URL/-/pipelines/$CI_PIPELINE_ID">#$CI_PIPELINE_ID</a></p>
+        </body>
+      </html>
+      EOF
+          exit 1
+      fi;
+  # Ideally, the job script should only fail on the last line.
+  # If the script exits at that stage, we still want to proceed to the deployment stage with what has already been built.
+  # This is a temporary solution to avoid rebuilding all of the apps if a few of them fail.
+  # In the future, each app should be built based on the changed files since its last valid version tag.
+  allow_failure: true
   artifacts:
     name: $CI_COMMIT_TAG-$CI_PIPELINE_ID
     when: always
