fix(ci): clean out-dir after publish

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -68,8 +68,8 @@ release-devops-packages:
     - corepack enable
     - npm install -g turbo
     # Authenticate
-    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
-    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
+    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
+    - echo "${CI_API_V4_URL#http*:}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}" >> .npmrc
     # Extract version segment from tag
     - export VERSION=${CI_COMMIT_TAG:7}
     # Publish all devops packages
@@ -81,19 +81,24 @@ release-devops-packages:
         PKG_VERSION=$(echo $PKG | jq -Mr .version)
         PKG_BUILD_PATH=$OUT_DIR/devops/$PKG_BASENAME
 
+        if [[ ! $NPM_PACKAGE_NAME =~ ^@$CI_PROJECT_ROOT_NAMESPACE/ ]]; then
+          echo "Invalid package scope! Packages must be scoped in the root namespace of the project, e.g. \"@${CI_PROJECT_ROOT_NAMESPACE}/$PKG\""
+          echo 'For more information, see https://docs.gitlab.com/ee/user/packages/npm_registry/#package-naming-convention'
+          exit 1
+        fi
+
         turbo prune --scope=$PKG_NAME --out-dir $OUT_DIR
         pnpm install -C $OUT_DIR
         pnpm run -C $OUT_DIR build
         if [[ $PKG_VERSION != $VERSION ]]; then
-          echo ""
-          echo "Version of package '$PKG_NAME' does not match given tag name."
+          echo "Version of package '$PKG_NAME' does not match given tag name. Modifying published package.json."
           echo "Tag version: $VERSION, Package Version: $PKG_VERSION"
-          echo ""
           tmp=$(mktemp)
           jq --arg version "$VERSION" '.version = $version' $PKG_BUILD_PATH/package.json > "$tmp"
           mv "$tmp" $PKG_BUILD_PATH/package.json
         fi
         pnpm publish --no-git-checks $PKG_BUILD_PATH
+        rm -r $OUT_DIR
       done
 
 release-apps:
