update

diff --git a/.github/workflows/teleskop-web-sandbox.yml b/.github/workflows/teleskop-web-sandbox.yml
--- a/.github/workflows/teleskop-web-sandbox.yml
+++ b/.github/workflows/teleskop-web-sandbox.yml
@@ -78,8 +78,9 @@ jobs:
       image: node:22
     if: ${{ needs.classify-ref.outputs.app_rules == 'true' }}
     timeout-minutes: 60
-    env:
-      TARGET_APPS: archive recipes dispensing-manager-ui communication-driver machine-status machines migration-service multi-monitor planning-board planning-board-engine root websockify program-editor
+    strategy:
+      matrix:
+        app: [archive, recipes, dispensing-manager-ui, communication-driver, machine-status, machines, migration-service, multi-monitor, planning-board, planning-board-engine, root, websockify, program-editor]
     steps:
       - run: apt-get update
       - run: apt-get install -y git-lfs
@@ -90,17 +91,13 @@ jobs:
           fetch-depth: 20
           lfs: true
       - run: npm install -g turbo@^2
-      - run: |
-          for APP_NAME in $TARGET_APPS; do
-            turbo prune --scope=$APP_NAME --out-dir out-$APP_NAME --docker
-          done
-      #     # 'artifacts.dotenv' was not transformed because there is no suitable equivalent in GitHub Actions
+      - run: turbo prune --scope=${{ matrix.app }} --out-dir out-${{ matrix.app }} --docker
       - uses: actions/upload-artifact@v4.1.0
         if: ${{ success() && !github.event.act }}
         with:
-          name: prepare-apps
+          name: app-${{ matrix.app }}
           retention-days: 1
-          path: prepared-apps/
+          path: out-${{ matrix.app }}/
           if-no-files-found: error
 
   prepare-hotfix:
@@ -168,8 +165,9 @@ jobs:
     permissions:
       contents: read
       packages: write
-    env:
-      TARGET_APPS: archive recipes dispensing-manager-ui communication-driver machine-status machines migration-service multi-monitor planning-board planning-board-engine root websockify program-editor
+    strategy:
+      matrix:
+        app: [archive, recipes, dispensing-manager-ui, communication-driver, machine-status, machines, migration-service, multi-monitor, planning-board, planning-board-engine, root, websockify, program-editor]
     steps:
       - uses: actions/checkout@v4.1.0
         with:
@@ -188,28 +186,26 @@ jobs:
       - run: mkdir release-logs
       - run: export ERRORS=""
       - run: |
-          for APP_NAME in $TARGET_APPS; do
-            LOG_PATH="release-logs/$APP_NAME.log"
-            ERR_PATH="release-logs/$APP_NAME.error.log"
-            EXIT_CODE=0
-            # Variables for docker bake
-            export APP_NAME="$APP_NAME"
-            export APP_ROLES="$(jq -Mc '.roles // []' "apps/$APP_NAME/manifest.json" 2> /dev/null || echo '[]')"
-            rm -rf out && mv out-$APP_NAME out
-            # Output build logs to both the console and a log file
-            {
-              docker buildx bake "$APP_NAME" --push 2>&1 || {
-                mv $LOG_PATH $ERR_PATH
-              }
-            } | tee $LOG_PATH
-            if [ -e "$ERR_PATH" ]; then
-              if [ -n "$ERRORS" ]; then
-                ERRORS="$ERRORS,$APP_NAME"
-              else
-                ERRORS="$APP_NAME"
-              fi
+          LOG_PATH="release-logs/${{ matrix.app }}.log"
+          ERR_PATH="release-logs/${{ matrix.app }}.error.log"
+          EXIT_CODE=0
+          # Variables for docker bake
+          export APP_NAME="$APP_NAME"
+          export APP_ROLES="$(jq -Mc '.roles // []' "apps/${{ matrix.app }}/manifest.json" 2> /dev/null || echo '[]')"
+          rm -rf out && mv out-${{ matrix.app }} out
+          # Output build logs to both the console and a log file
+          {
+            docker buildx bake "${{ matrix.app }}" --push 2>&1 || {
+              mv $LOG_PATH $ERR_PATH
+            }
+          } | tee $LOG_PATH
+          if [ -e "$ERR_PATH" ]; then
+            if [ -n "$ERRORS" ]; then
+              ERRORS="$ERRORS,$APP_NAME"
+            else
+              ERRORS="$APP_NAME"
             fi
-          done
+          fi
       - run: |
           if [ -n "$ERRORS" ]; then
             if [ -n "$SMTP_CONF" ]; then
@@ -265,14 +261,14 @@ jobs:
       - run: mkdir release-logs
       - run: export ERRORS=""
       - run: export APP_NAME=$(echo ${{ github.ref }} | sed -E 's/^([a-z._-]+)@.*/\1/')
-      - run: export APP_ROLES="$(jq -Mc '.roles // []' "apps/$APP_NAME/manifest.json" 2> /dev/null || echo '[]')"
+      - run: export APP_ROLES="$(jq -Mc '.roles // []' "apps/${{ matrix.app }}/manifest.json" 2> /dev/null || echo '[]')"
       - run: |
           {
-            docker buildx bake "$APP_NAME" --push 2>&1 || {
-              mv "release-logs/$APP_NAME.log" "release-logs/$APP_NAME.error.log"
+            docker buildx bake "${{ matrix.app }}" --push 2>&1 || {
+              mv "release-logs${{ matrix.app }}.log" "release-logs/${{ matrix.app }}.error.log"
               exit 1
             }
-          } | tee "release-logs/$APP_NAME.log"
+          } | tee "release-logs/${{ matrix.app }}.log"
       - uses: actions/upload-artifact@v4.1.0
         if: always()
         with:
